### ISSUE TITLE
Huge tracking error / delay (off-line planned trajectories, JointTrajectoryController)

### ISSUE THREAD

**Issue by aatb-ch** [ros-industrial/abb_robot_driver#41]
I have used successfully the driver with our IRB4600 over EGM by using a `position_controllers/JointTrajectoryController`, and a `velocity_controllers/JointTrajectoryController`. I am now trying to optimize the configuration to very closely follow highly-dynamic trajectories and so have been reading around, for example this issue https://github.com/ros-industrial/abb_libegm/issues/111. The `config.base.use_velocity_outputs = true` allows to send velocity data, and I noticed that it is enabled by default in the driver and writes velocity commands if passed by the controller, like with a `velocity_controller`.

Unless I've misunderstood Position controllers, they will not forward anything else besides position commands, correct? How should I go about including the velocity data as well without having a PID? Is there any existing method, or trajectory controller available for that? Am I supposed to write my own controller? I have seen the PosVel interface is already implemented in the driver, but I just can not find any information on existing `pos_vel_controllers` implementation, I've naively tried to use a `pos_vel_controllers/JointTrajectoryController` but it wildy overshoots and seems like a PID is running on top of it, I just want to simply forward the splined trajectory as-is.

**Comment by aatb-ch** [comment]
Following up on my previous question, I had a previous homemade implementation of the EGM driver that was simply streaming position setpoints at 4ms, from pregenerated trajectories in a 3d animation software. The robot in RobotStudio perfectly tracks this trajectory, while it completely drifts behind and lags behind target when importing the same trajectory to the joint_trajectory_controller. I have tried importing only pos, pos+vel and pos+vel+acc, no difference. I have tried `position_controllers`, `velocity_controllers` with PID, changed tuning parameters, with/without `velocity_ff`, `pos_vel_controllers` and neither of them is able to follow the trajectory even close to accurately. Keep in mind I'm specifically discussing highly-dynamic movements, with short accelerations and reaching as close as maximum rater joint speeds. The robot is perfectly capable of doing that in RAPID, but it should be also able to do that over EGM at 250Hz control.

I am starting to wonder if this could come from `abb_libegm` ? Seems like the joints are somehow not accelerating as fast as they could, it ramps linearly as if artificially limited, it takes almost 0.4s to go from 0 to 3rad/s, which seems.. slow? I am using no filtering (level 0 RAW), position gain 20 and correction gain 1, which should be the maximum possible.

![Screenshot from 2022-02-16 10-48-20](https://user-images.githubusercontent.com/60657807/154287802-121dd070-24ac-423b-a8a9-2fc0c736baa9.png)

**Comment by gavanderhoorn** [comment]
The driver attempts to enforce joint limits in a few places, one of which is here for velocity interfaces:

https://github.com/ros-industrial/abb_robot_driver/blob/72c71f7d85e4896e34b5cd8ec68c73c409756006/abb_egm_hardware_interface/src/egm_hardware_interface.cpp#L265-L269

You don't give any information on how you've configured things on the ROS side, so I cannot say this is affecting you or not.

It's also unclear to me how you've configured EGM on the controller exactly. Showing the output of the `rws/get_egm_settings` service (such as shown in https://github.com/ros-industrial/abb_robot_driver/issues/16#issuecomment-790516237) could help spot something.

(one thing I've often seen fi with velocity is people not setting `pos_corr_gain` to `0`)

**Comment by aatb-ch** [comment]
So i'm going down the rabbit hole, if I understand correctly, the trajectory interface for `abb_libemg` applies linear velocity transitions between goals?

https://github.com/ros-industrial/abb_libegm/blob/ab40aec4fd79e24e3d342d87b41f8375991a1f04/src/egm_trajectory_interface.cpp#L602

If someone with knowledge of the internals of the `abb_libegm` driver could confirm what I suspect, that would be extremely nice, and also how to bypass that as this totally breaks my use-case if this is the case.

**Comment by aatb-ch** [comment]
Yes I have already confirmed that the joint position and velocity limits are correct, and these are not exceeded. The issue seems related to the acceleration of the joints.

Here is the full configuration I send before starting the EGM session:

```
rosservice call /rws/sm_addin/set_egm_settings "task: T_ROB1
settings:
  allow_egm_motions: True
  use_presync: False
  setup_uc:
    use_filtering: False
    comm_timeout: 1.0
  activate:
    tool:
      robhold: True
      tframe:
        trans:
          x: 0.0
          y: 0.0
          z: 150.0
        rot:
          q1: 1.0
          q2: 0.0
          q3: 0.0
          q4: 0.0
      tload:
        mass: 1
        cog:
          x: 0.0
          y: 0.0
          z: 10.0
        aom:
          q1: 1.0
          q2: 0.0
          q3: 0.0
          q4: 0.0
        ix: 0.0
        iy: 0.0
        iz: 0.0
    wobj:
      robhold: False
      ufprog: True
      ufmec: ''
      uframe:
        trans:
          x: 0.0
          y: 0.0
          z: 0.0
        rot:
          q1: 1.0
          q2: 0.0
          q3: 0.0
          q4: 0.0
      oframe:
        trans:
          x: 0.0
          y: 0.0
          z: 0.0
        rot:
          q1: 1.0
          q2: 0.0
          q3: 0.0
          q4: 0.0
    correction_frame:
      trans:
        x: 0.0
        y: 0.0
        z: 0.0
      rot:
        q1: 1.0
        q2: 0.0
        q3: 0.0
        q4: 0.0
    sensor_frame:
      trans:
        x: 0.0
        y: 0.0
        z: 0.0
      rot:
        q1: 1.0
        q2: 0.0
        q3: 0.0
        q4: 0.0
    cond_min_max: 0.1
    lp_filter: 100.0
    sample_rate: 4
    max_speed_deviation: 1000.0
  run:
    cond_time: 36000.0
    ramp_in_time: 1.0
    offset:
      trans:
        x: 0.0
        y: 0.0
        z: 0.0
      rot:
        q1: 1.0
        q2: 0.0
        q3: 0.0
        q4: 0.0
    pos_corr_gain: 1.0
  stop:
    ramp_out_time: 1.0"
```
 
If I am on the right track, it seems that the joint acceleration is hardcoded in the abb_libegm driver here:

https://github.com/ros-industrial/abb_libegm/blob/ab40aec4fd79e24e3d342d87b41f8375991a1f04/src/egm_trajectory_interface.cpp#L583

And this acceleration value `a_` is then used to interpolate velocity between goals

https://github.com/ros-industrial/abb_libegm/blob/ab40aec4fd79e24e3d342d87b41f8375991a1f04/src/egm_trajectory_interface.cpp#L602

And here

https://github.com/ros-industrial/abb_libegm/blob/ab40aec4fd79e24e3d342d87b41f8375991a1f04/src/egm_trajectory_interface.cpp#L664

Which would explain the linear ramp that the joint velocity follows in my previous rqt_plot screenshot, does that make any sense?

**Comment by aatb-ch** [comment]
And specifically for velocity_controllers I tried with both `pos_corr_gain`: 0.0 and 1.0. Weirdly when using the velocity_controllers this had a large impact, but I though that position_controllers and velocity_controllers would output either only position corrections (`EgmPlanned` message) or velocity (`SpeedRef` message) but it seems that the `velocity_controller` sends both position and velocity as it was working quite fine, albeit more smooth with pure velocity control.

**Comment by gavanderhoorn** [comment]
First: this part was written by @jontje, so I'm not able to give you an authoritative answer here.

From reading the code it does appear acceleration ramping is implemented in `abb_libegm`. However, I'm not sure the `EGMTrajectoryInterface` is used by `EGMHardwareInterface`.

Afaik (and IIRC), the driver uses an abstraction called `EGMManager`, which manages a set of `Channel`s (and associated Configurations). Those are used directly to read/write state data/new references. I don't see any reference (directly or indirectly) to the `EGMTrajectoryInterface`. That's mainly for use by stand-alone programs.

Using the trajectory interface (from `abb_libegm`) would also seem like it would not work: `ros_control` controllers are already capable of interpolating between setpoints, and that's essentially what the `EGMTrajectoryInterface` does.

> And specifically for `velocity_controllers` I tried with both `pos_corr_gain`: 0.0 and 1.0. 

pure velocity controllers should not work with `pos_corr_gain == 1.0`. The ABB controller would 'fight' with the incoming velocity references and try to overlay / return to a position command.

> Weirdly when using the `velocity_controllers` this had a large impact, but I though that `position_controllers` and `velocity_controllers` would output either only position corrections (`EgmPlanned` message) or velocity (`SpeedRef` message)

`ros_control` controllers don't know anything about EGM, so they don't "output either only position corrections (`EgmPlanned` message) or velocity (`SpeedRef` message)".

Controllers in the `velocity_controllers` package write velocity references to the underlying hw interface. Either as part of a position controller implemented over a velocity interface or as a forwarding controller, which just forwards incoming setpoints directly to the hw interface.

Controllers in the `position_controllers` package write position references to the underlying hw interface. There are only forwarding implementations available there, no closed-loops.

> but it seems that the `velocity_controller` sends both position and velocity 

no, it really doesn't.

Also: `velocity_controllers` is a *package*, not a controller. See my earlier comment on this.

> as it was working quite fine, albeit more smooth with pure velocity control.

I'm confused by your statements.

It's been a while, but without setting `pos_corr_gain` to `0.0`, the `velocity_controllers/JointTrajectoryController` (fi) will not work correctly.

**Comment by gavanderhoorn** [comment]
> Yes I have already confirmed that the joint position and velocity limits are correct, and these are not exceeded.

Could you show what you've configured exactly?

Do you also set acceleration limits?

**Comment by gavanderhoorn** [comment]
Joint limits are in radians and radians/sec. The values you show don't make too much sense to me.

> Yes I noticed that any acceleration limits would be ignored, but is there some default one that might be applied?

Not according to what I can find in `joint_limits_interface.h`, but it's easy to test: comment these lines and rebuild the driver:

https://github.com/ros-industrial/abb_robot_driver/blob/72c71f7d85e4896e34b5cd8ec68c73c409756006/abb_egm_hardware_interface/src/egm_hardware_interface.cpp#L265-L269

be sure to not command anything going over the limits though. I'm not responsible for any damage you cause to your hw.

**Comment by aatb-ch** [comment]
> Btw, just to clarify: I'm not dismissing your observations.
> 
> I'm just confused by various statements you've made.

No problem. I just tested again and can confirm that the `velocity_controllers/JointTrajectoryController` behaves exactly the same if using `pos_corr_gain` 0 or 1.

```
velocity_joint_trajectory_controller:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
   - joint_1
   - joint_2
   - joint_3
   - joint_4
   - joint_5
   - joint_6
  gains: # Required because we're controlling a velocity interface
    joint_1: {p: 4,  d: 0.1, i: 0, i_clamp: 0.1} # Smaller 'p' term, since ff term does most of the work
    joint_2: {p: 4,  d: 0.1, i: 0, i_clamp: 0.1} # Smaller 'p' term, since ff term does most of the work
    joint_3: {p: 4,  d: 0.1, i: 0, i_clamp: 0.1} # Smaller 'p' term, since ff term does most of the work
    joint_4: {p: 4,  d: 0.1, i: 0, i_clamp: 0.1} # Smaller 'p' term, since ff term does most of the work
    joint_5: {p: 4,  d: 0.1, i: 0, i_clamp: 0.1} # Smaller 'p' term, since ff term does most of the work
    joint_6: {p: 4,  d: 0.1, i: 0, i_clamp: 0.1} # Smaller 'p' term, since ff term does most of the work
  velocity_ff:
    joint_1: 1
    joint_2: 1
    joint_3: 1
    joint_4: 1
    joint_5: 1
    joint_6: 1
  stop_trajectory_duration: 0.5
  state_publish_rate: 250
  action_monitor_rate: 20
```

Regarding limits, my bad. I read them here https://github.com/ros-industrial/abb_robot_driver/blob/master/abb_robot_bringup_examples/config/ex2_hardware_egm.yaml and assumed they were in deg/s as as I was reading the EGM docs stating MaxSpeedDeviation is 1deg/s, mixup on my side.

I'll try commenting out the limits to see, anyway I'm only working in RobotStudio right now, this is only to figure out where the different behavior is from, we'll not run any of this on the real robot until we're clear what's the issue.
